sudo: false
language: go
go: 1.4

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/davecgh/go-spew/spew

script:
  - make check test
