#!/bin/bash -e

# standardize on gnu sort where available
ssort() {
    if hash gsort 2>/dev/null; then
        gsort "$@"
    else
        sort "$@"
    fi
}

file="$(git rev-parse --show-toplevel)/CONTRIBUTORS"

cat <<EOF > "$file"
# People who can (and typically have) contributed to this repository.
#
# This script is generated by $(basename "$0")
#

EOF

git log --format='%aN <%aE>' | ssort -uf >> "$file"
